package com.jeta.forms.support;

import com.jeta.forms.gui.common.FormUtils;

/**
 * AbeilleForms.java is an automatically generated java file. If you want to
 * make changes, you must edit the AbeilleForms.txt file. The build script will
 * read the file and generate the corresponding Java File
 * 
 * Some global constants and declarations for this application.
 * 
 * @author Jeff Tassin
 */
public class AbeilleForms {

	/**
	 * @return a version string for the application
	 */
	public static String getVersion() {
		StringBuffer buffer = new StringBuffer();
		// buffer.append( "Beta " );
		buffer.append(MAJOR_VERSION);
		buffer.append(".");
		buffer.append(MINOR_VERSION);
		buffer.append(".");
		buffer.append(SUBMINOR_VERSION);
		buffer.append(".");
		return buffer.toString();
	}


	
	/**
	 * @return a version string relevant for use within a Frame's titlebar.
	 */
	public static String getVersionTitle() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(MAJOR_VERSION);
		buffer.append(".");
		buffer.append(MINOR_VERSION);
		buffer.append(".");
		buffer.append(SUBMINOR_VERSION);
		return buffer.toString();
	}

	/* do not add anything below this line - auto generated by build script */

     public static int MAJOR_VERSION = 3;
     public static int MINOR_VERSION = 0;
     public static int SUBMINOR_VERSION = 0;
 

}