/* 
 * Copyright 2004 JETA Software, Inc. All rights reserved.
 * JETA SOFTWARE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/* Generated by Together */

package com.jeta.swingbuilder.codegen.builder;

public interface Statement extends Expression {
	void output(SourceBuilder builder);
}
